---
title: "custeio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r libraries,  message=FALSE}
library(flexdashboard)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(knitr)
library(shiny)
library(shinyWidgets)
library(lubridate)
library(tidyverse)
library(janitor)
library(googledrive)
library(gargle)
library(GetBCBData)

```


```{r}
nomenclatura <- read_excel("nomenclatura.xlsx")
```

```{r}
custeio_historico <- read_excel("custeio_historico.xlsx")

colnames(custeio_historico)<-c("uo_cod", "uo", "ano","ndd_cod", "ndd", "custeio")
```


```{r}


custeio_historico_2018 <- read_excel("custeio historico_2018.xlsx")
custeio_historico_2019 <- read_excel("custeio historico_2019.xlsx")
custeio_historico_2020 <- read_excel("custeio historico_2020.xlsx")

base <- rbind(custeio_historico_2018,custeio_historico_2019,custeio_historico_2020) 




colnames(base)<-c("uo_cod", "uo", "mes","ndd_id", "ndd", "custeio")

# base <- base %>% filter(mes != "201813")

base <- base %>% filter(!endsWith(mes,"13"))
colnames(base)<-c("uo_cod", "uo", "mes","ndd_id", "ndd", "custeio")

base<- full_join (base,nomenclatura %>% select(-ndd) ,  by = c("ndd_id" = "ndd_id"))

base <-  base %>%    mutate( ref.date = parse_date_time( base$mes, "ym"))%>% drop_na()



```


```{r}

plot_custeio <- base  %>% mutate(ano = year(ref.date)) %>% group_by(tipo_custeio, ano) %>% summarise(custeio = sum(custeio))

historico <- ggplot(plot_custeio, aes(x= ano , y = custeio, fill = tipo_custeio))+
  geom_col()

historico




 
 
 (ggplot( base  %>% mutate(ano = year(ref.date)) %>% group_by(uo, ano) %>% summarise(custeio = sum(custeio)), aes(x= reorder (uo, custeio) , y = custeio))+
  geom_col()+ coord_flip())



 (ggplot( base  %>% mutate(ano = year(ref.date)) %>% group_by(tipo_custeio, ano) %>% summarise(custeio = sum(custeio)), aes(x= reorder (tipo_custeio, custeio ), y = custeio))+
  geom_col()+ coord_flip())
```


```{r}
inflacao <- c('IPCA')
my.ids <- c(433)
names(my.ids) <- paste0( inflacao)
df.bcb <- gbcbd_get_series(id = my.ids ,
                       first.date = '2000-01-01',
                       last.date = Sys.Date(),
                       format.data = 'long',
                       use.memoise = TRUE, 
                       cache.path = tempdir(), # use tempdir for cache folder
                       do.parallel = FALSE)
glimpse(df.bcb)
p <- ggplot(df.bcb, aes(x = ref.date, y = value) ) +
  geom_line() + 
  labs(title = 'Inflação', 
       subtitle = paste0(min(df.bcb$ref.date), ' to ', max(df.bcb$ref.date)),
       x = '', y = 'Percentage*100') + facet_wrap(~series.name)
  
print(p)
```
```{r eval=FALSE, include=FALSE}
ufsc <- read_excel("ufsc.xlsx")



colnames(ufsc)<-c( "mes","ndd_cod", "ndd", "custeio")

# base <- base %>% filter(mes != "201813")

base <- base %>% filter(!endsWith(mes,"13"))
colnames(base)<-c("uo_cod", "uo", "mes","ndd_cod", "ndd", "custeio")


```


```{r}
(df.bcb %>% filter( ref.date > "2020-05-01") %>% group_by(series.name) %>% summarise(acumulado = prod(1+value/100)-1))
```

