 
---
title: "CUSTEIO"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: https://github.com/andreferraribr/custeio
    social:
    - twitter
    - facebook
    - menu
runtime: shiny

---


```{r setup, include=FALSE}
options(scipen=999)
options(digits=2)
# options (LC_NUMERIC="pt_BR.UTF-8")
```

```{r}
```



```{r libraries,  message=FALSE}
library(flexdashboard)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(shiny)
library(shinyWidgets)
library(lubridate)
library(tidyverse)
library(janitor)
library(scales)
library(GetBCBData)
```



```{r negar %in%}
# https://www.r-bloggers.com/the-notin-operator/
'%!in%' <- Negate('%in%')
```


```{r}
# criar funções para apresentar a unidade de medida e converter automaticamente para milhares, milhões, bilhões e trilhões
escala <- function(x){case_when(
  abs(x) < 1000 ~ "",
  abs(x) >= 1000  & abs(x) < 1000000 ~ "K",
  abs(x) >= 1000000  & abs(x) < 1000000000 ~ "Mi",
  abs(x) >= 1000000000  & abs(x) < 1000000000000 ~ "Bi",
  abs(x) >= 1000000000000  & abs(x) < 1000000000000000 ~ "trilhão",
  TRUE ~ "maior que trilhão"
)}
 escala <- Vectorize(escala)
divisor <- function(x){case_when(
  abs(x) < 1000 ~ x,
  abs(x) >= 1000  & abs(x) < 1000000 ~ round(x/1000,digits = 1),
  abs(x) >= 1000000  & abs(x) < 1000000000 ~ round(x/1000000, digits = 1),
  abs(x) >= 1000000000  & abs(x) < 1000000000000 ~ round (x/1000000000, digits = 1),
  abs(x) >= 1000000000000  & abs(x) < 1000000000000000 ~ round (x/1000000000000, digits = 1),
  TRUE ~ x
)}
 divisor <- Vectorize(divisor)
```



```{r eval=FALSE, include=FALSE}
nomenclatura <- read_excel("nomenclatura.xlsx")
```


```{r eval=FALSE, include=FALSE}


# custeio_historico_2018 <- read_excel("custeio historico_2018.xlsx")
custeio_historico_2019 <- read_excel("custeio historico_2019.xlsx")
custeio_historico_2020 <- read_excel("custeio historico_2020.xlsx")
custeio_historico_2021 <- read_excel("custeio historico_2021.xlsx")

base <- rbind(custeio_historico_2019,custeio_historico_2020,custeio_historico_2021) 




colnames(base)<-c("uo_cod", "uo", "mes","ndd_id", "ndd", "custeio")

# base <- base %>% filter(mes != "201813")

base <- base %>% filter(!endsWith(mes,"13"))
colnames(base)<-c("uo_cod", "uo", "mes","ndd_id", "ndd", "custeio")

base<- full_join (base,nomenclatura %>% select(-ndd) ,  by = c("ndd_id" = "ndd_id"))

base <-  base %>%    mutate( ref.date = parse_date_time( base$mes, "ym"))%>% drop_na() 


base <- base %>%  filter( ref.date >= max(ref.date)-months(23))%>% group_by(uo_cod, uo, tipo_custeio, ref.date)  %>% summarise( custeio = sum(custeio))



base <- base %>% mutate(periodo = if_else(ref.date < max(base$ref.date)-months(11), "atual", "anterior") )

 teste <- base  %>% group_by(uo, uo_cod, tipo_custeio, periodo) %>% summarise(custeio= sum(custeio)) %>%  pivot_wider(names_from = "periodo", values_from= "custeio")%>% 
  mutate_all(coalesce, 0)



```

```{r eval=FALSE, include=FALSE}
inflacao <- c('IPCA')
my.ids <- c(433)
names(my.ids) <- paste0( inflacao)
df.bcb <- gbcbd_get_series(id = my.ids ,
                       first.date = '2010-01-01',
                       last.date = Sys.Date(),
                       format.data = 'long',
                       use.memoise = TRUE, 
                       cache.path = tempdir(), # use tempdir for cache folder
                       do.parallel = FALSE)




  df.bcb <-  df.bcb %>%  filter( ref.date >= max(base$ref.date)-months(11)) %>%group_by(ref.date) %>% summarise( value = max(value))




# movel <- base %>% filter( ref.date >= max(ref.date)-months(23))%>% group_by(ref.date)  %>% summarise( custeio = sum(custeio))
# 
# # (base %>% filter( ref.date > max(base$ref.date)-months(12) ) %>% group_by(ref.date) %>% summarise(custeio= sum(custeio)))
# 
# # (base %>% filter( ref.date > max(base$ref.date)-months(24) & ref.date < max(base$ref.date)-months(11) ) %>% group_by(ref.date) %>% summarise(custeio= sum(custeio)))
# 
# movel <- left_join(movel, df.bcb)

# (sum(movel$custeio[13:24])/sum(movel$custeio[1:12]))-1
# 
# (cumprod(prod(1+movel$value[13:24]/100)-1))


# base <- left_join(base,df.bcb)
```


Filtro {.sidebar data-width=400}
=====================================
```{r}

base_app <- read_csv("base_app.csv")



df.bcb <- read_csv("bcb.csv")

pickerInput("sigla","Selecione o órgão", unique(base_app$sigla), selected =unique(base_app$sigla) ,
            options = list(`actions-box` = TRUE),
            width = 400,
            multiple = T)


pickerInput("tipo_desc","Selecione o tipo de custeio", unique(base_app$tipo_desc), selected =unique(base_app$tipo_desc) , options = list(`actions-box` = TRUE),width = 400,multiple = T)


base_react <- reactive(base_app %>% filter(sigla %in% input$sigla, tipo_desc %in% input$tipo_desc))


base_percentual <- reactive(base_react() %>% group_by(sigla, uo, uo_cod) %>% summarise(atual = sum(atual), anterior= sum(anterior)) %>% mutate(percentual = (atual/anterior-1)*100) %>% mutate(nominal = atual-anterior))

base_custeio <- reactive(base_react() %>% group_by( tipo_desc) %>% summarise(atual = sum(atual), anterior= sum(anterior)) %>% mutate(percentual = (atual/anterior-1)*100) %>% mutate(nominal = atual-anterior))
```


## Metodolodia

* Fonte SIAFI  

* Visão por UO do órgão máximo

* Saldo dos pagamentos totais (LOA + RP) 
 

 
  
* [Custeio Administrativo](https://www.gov.br/economia/pt-br/centrais-de-conteudo/publicacoes/boletins/boletim-de-custeio-administrativo/arquivos/2019/notametodologicacusteioadministrativo_2018_2019.pdf)  
  
 

Visão Geral
=============================================


Row 
-----------------------------------------------------------------------

### Custeio nos ultimos 12 meses 



```{r value custo pessoal UDs}





renderValueBox({
  
  
  # (base %>% filter( ref.date > max(base$ref.date)-months(12) ) %>% group_by(ref.date) %>% summarise(custeio= sum(custeio)))

# (base %>% filter( ref.date > max(base$ref.date)-months(24) & ref.date < max(base$ref.date)-months(11) ) %>% group_by(ref.date) %>% summarise(custeio= sum(custeio)))
  
 
 
 valor <- sum(base_react()$atual )
  
  # valor <- sum(movel$custeio[13:24])
 valueBox( # utilizar funções divisor() e escala () para converter automaticamente valores para milhar, milhão, bilhão...  
    paste0("R$ ", divisor(valor)," ",  escala(valor)),
  color = "red",
  caption = paste0( "de ", month(max(df.bcb$ref.date)) ,"-",year(max(df.bcb$ref.date))))
  })

```

### Varianca em R$ nominais

```{r value custo pessoalHKHI UDs}
renderValueBox({
  

  valor <- sum(base_react()$atual )-sum(base_react()$anterior )
 valueBox( paste0("R$ ", divisor(valor)," ",  escala(valor)),
  color = "red")
  })

```



### Variacao %




```{r value custo pessoalKHK UDs}
renderValueBox({
 valueBox( round((sum(base_react()$atual )/sum(base_react()$anterior)-1)*100,2),
  color = "red",
  
  caption = "variacao")
  })



```


### IPCA

```{r value custo pessoalNNN UDs}
renderValueBox({
 valueBox( round(((prod(1+df.bcb$value/100)-1))*100,2),
  color = "red")
  })

```

Row 
-----------------------------------------------------------------------


### Ranking custo total em R$ milhões




```{r plot custo total UDs}
renderPlotly(
  
    
ggplot(base_percentual()   , aes(x = reorder (sigla,(-nominal)), y = round((nominal)/1000000,1)))+ coord_flip() + 
    geom_col(fill = if_else( base_percentual()$nominal >0,"red", "blue"))+
  theme_classic()+
    
   theme(
     # axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank()))
```

### Ranking custeio administrativo em R$ milhões


```{r plot custeio UDs}
renderPlotly(
  
    
ggplot(base_percentual()    , aes(x = reorder (sigla,(-percentual)), y = percentual))+ coord_flip() + 
    geom_col(fill = if_else( base_percentual()$percentual >0,"red", "blue"))+
  theme_classic()+
    
   theme(
     # axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank()))
```

### Ranking custo com pessoal em R$ milhões



```{r plot custo pessoal uds, echo=FALSE}
renderPlotly(
  
    
ggplot(base_custeio()   , aes(x = reorder (tipo_desc,(-nominal)), y = round((nominal)/1000000,1)))+ coord_flip() + 
    geom_col(fill = if_else( base_custeio()$nominal >0,"red", "blue"))+
  theme_classic()+
    
   theme(
     # axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank()))
```



### Ranking comissão


```{r plot comissao}
renderPlotly(
  
    
ggplot(base_custeio()    , aes(x = reorder (tipo_desc,(-percentual)), y = percentual))+ coord_flip() + 
    geom_col(fill = if_else( base_custeio()$percentual >0,"red", "blue"))+
  theme_classic()+
    
   theme(
     # axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank()))
```



